.\"	$Surreal: daemon.8,v 1.1.1.1 2009/08/26 07:41:22 mitya Exp $
.\"
.\" Copyright (c) 2006, 2007 Dmitri Alenichev <mitya@sdf.lonestar.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd December 30, 2006
.Dt DAEMON 8
.Os
.Sh NAME
.Nm daemon
.Nd run detached from the controlling terminal
.Sh SYNOPSIS
.Nm daemon
.Op Fl cf
.Op Fl g Ar group
.Op Fl p Ar pidfile
.Op Fl u Ar user
.Ar command arguments ...
.Sh DESCRIPTION
The
.Nm
utility detaches itself from the controlling terminal and
executes the program specified by its arguments. Privileges may
be lowered to the specified user and/or group.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Change the current working directory to the root.
.It Fl f
Redirect standard input, standard output and standard error to
.Pa /dev/null .
.It Fl g Ar group
Drop privileges to specified group.
.It Fl p Ar file
Write the PID of created process into the file.
.It Fl u Ar user
Drop privileges to specified user.
.El
.Sh DIAGNOSTICS
If the command cannot be executed, an error message is displayed on
standard error unless the
.Fl f
option is specified.
.Sh SEE ALSO
.Xr setgid 2 ,
.Xr setuid 2 ,
.Xr daemon 3 ,
.Xr exec 3
.Sh AUTHORS
The
.Nm
program was written by
.An Dmitri Alenichev
.Aq mitya@sdf.lonestar.org .
